// Copyright 2025 Bryan Wong
#pragma once

// IWYU pragma: begin_exports
#include "rxx/algorithm/adjacent_find.h"
#include "rxx/algorithm/all_of.h"
#include "rxx/algorithm/any_of.h"
#include "rxx/algorithm/binary_search.h"
#include "rxx/algorithm/contains.h"
#include "rxx/algorithm/copy.h"
#include "rxx/algorithm/count.h"
#include "rxx/algorithm/ends_with.h"
#include "rxx/algorithm/fill.h"
#include "rxx/algorithm/find.h"
#include "rxx/algorithm/find_end.h"
#include "rxx/algorithm/find_first_of.h"
#include "rxx/algorithm/find_last.h"
#include "rxx/algorithm/fold.h"
#include "rxx/algorithm/for_each.h"
#include "rxx/algorithm/generate.h"
#include "rxx/algorithm/heap_operations.h"
#include "rxx/algorithm/minmax.h"
#include "rxx/algorithm/mismatch.h"
#include "rxx/algorithm/move.h"
#include "rxx/algorithm/none_of.h"
#include "rxx/algorithm/partition.h"
#include "rxx/algorithm/permutation.h"
#include "rxx/algorithm/remove.h"
#include "rxx/algorithm/remove_copy.h"
#include "rxx/algorithm/replace.h"
#include "rxx/algorithm/replace_copy.h"
#include "rxx/algorithm/return_types.h"
#include "rxx/algorithm/reverse.h"
#include "rxx/algorithm/reverse_copy.h"
#include "rxx/algorithm/rotate.h"
#include "rxx/algorithm/rotate_copy.h"
#include "rxx/algorithm/sample.h"
#include "rxx/algorithm/search.h"
#include "rxx/algorithm/search_n.h"
#include "rxx/algorithm/set_operations.h"
#include "rxx/algorithm/shift.h"
#include "rxx/algorithm/sort.h"
#include "rxx/algorithm/starts_with.h"
#include "rxx/algorithm/swap_ranges.h"
#include "rxx/algorithm/transform.h"
#include "rxx/algorithm/unique.h"
#include "rxx/algorithm/unique_copy.h"
// IWYU pragma: end_exports
