/* Copyright 2023-2025 Bryan Wong */

#pragma once

#include "rxx/configuration/compiler.h"
#include "rxx/configuration/declspec.h"
#include "rxx/preprocessor/apply_macro.h"
#include "rxx/preprocessor/concatenation.h"
#include "rxx/preprocessor/is_empty.h"
#include "rxx/preprocessor/paste.h"

#define __RXX_CPP_ATTRIBUTE_SCOPE_1()
#define __RXX_CPP_ATTRIBUTE_SCOPE_0(...) [[__VA_ARGS__]]
#define __RXX_CPP_ATTRIBUTE_SCOPE(...)                                      \
    RXX_PASTE(RXX_APPEND_IS_EMPTY(__RXX_CPP_ATTRIBUTE_SCOPE_, __VA_ARGS__)( \
        __VA_ARGS__))

#define __RXX_GNU_ATTRIBUTE_SCOPE_1()
#define __RXX_GNU_ATTRIBUTE_SCOPE_0(...) __attribute__((__VA_ARGS__))
#define __RXX_GNU_ATTRIBUTE_SCOPE(...)                                      \
    RXX_PASTE(RXX_APPEND_IS_EMPTY(__RXX_GNU_ATTRIBUTE_SCOPE_, __VA_ARGS__)( \
        __VA_ARGS__))

#define __RXX_DECLSPEC_SCOPE_1()
#define __RXX_DECLSPEC_SCOPE_0(...) __declspec(__VA_ARGS__)
#define __RXX_DECLSPEC_SCOPE(...) \
    RXX_PASTE(                    \
        RXX_APPEND_IS_EMPTY(__RXX_DECLSPEC_SCOPE_, __VA_ARGS__)(__VA_ARGS__))

#define __RXX_TRANSLATE_ATTRIBUTE(ARGS) \
    RXX_SWAP_CONCAT(_END, __RXX_TRANSLATE_ATTRIBUTE_1 ARGS)
#define __RXX_TRANSLATE_ATTRIBUTE_0(NAME) (RXX_CONCAT(__RXX_ATTRIBUTE_, NAME))
#if RXX_MSVC_PREPROCESSOR
#  define __RXX_TRANSLATE_ATTRIBUTE_1(NAME) \
      RXX_PASTE(__RXX_TRANSLATE_ATTRIBUTE_0(NAME) __RXX_TRANSLATE_ATTRIBUTE_2)
#  define __RXX_TRANSLATE_ATTRIBUTE_2(NAME) \
      RXX_PASTE(__RXX_TRANSLATE_ATTRIBUTE_0(NAME) __RXX_TRANSLATE_ATTRIBUTE_1)
#else
#  define __RXX_TRANSLATE_ATTRIBUTE_1(NAME) \
      __RXX_TRANSLATE_ATTRIBUTE_0(NAME) __RXX_TRANSLATE_ATTRIBUTE_2
#  define __RXX_TRANSLATE_ATTRIBUTE_2(NAME) \
      __RXX_TRANSLATE_ATTRIBUTE_0(NAME) __RXX_TRANSLATE_ATTRIBUTE_1
#endif
#define __RXX_TRANSLATE_ATTRIBUTE_1_END
#define __RXX_TRANSLATE_ATTRIBUTE_2_END

#define __RXX_BUILD_ATTRIBUTE_LIST(ARGS) \
    RXX_SWAP_CONCAT(_END, __RXX_BUILD_ATTRIBUTE_LIST_1 ARGS)
#define __RXX_BEGIN_ATTRIBUTE_LIST(NAME) NAME
#define __RXX_APPEND_ATTRIBUTE(NAME) , NAME
#if RXX_MSVC_PREPROCESSOR
#  define __RXX_BUILD_ATTRIBUTE_LIST_1(MEMBER) \
      RXX_PASTE(__RXX_BEGIN_ATTRIBUTE_LIST(MEMBER) __RXX_BUILD_ATTRIBUTE_LIST_2)
#  define __RXX_BUILD_ATTRIBUTE_LIST_2(MEMBER) \
      RXX_PASTE(__RXX_APPEND_ATTRIBUTE(MEMBER) __RXX_BUILD_ATTRIBUTE_LIST_3)
#  define __RXX_BUILD_ATTRIBUTE_LIST_3(MEMBER) \
      RXX_PASTE(__RXX_APPEND_ATTRIBUTE(MEMBER) __RXX_BUILD_ATTRIBUTE_LIST_2)
#else
#  define __RXX_BUILD_ATTRIBUTE_LIST_1(MEMBER) \
      __RXX_BEGIN_ATTRIBUTE_LIST(MEMBER) __RXX_BUILD_ATTRIBUTE_LIST_2
#  define __RXX_BUILD_ATTRIBUTE_LIST_2(MEMBER) \
      __RXX_APPEND_ATTRIBUTE(MEMBER) __RXX_BUILD_ATTRIBUTE_LIST_3
#  define __RXX_BUILD_ATTRIBUTE_LIST_3(MEMBER) \
      __RXX_APPEND_ATTRIBUTE(MEMBER) __RXX_BUILD_ATTRIBUTE_LIST_2
#endif
#define __RXX_BUILD_ATTRIBUTE_LIST_1_END
#define __RXX_BUILD_ATTRIBUTE_LIST_2_END
#define __RXX_BUILD_ATTRIBUTE_LIST_3_END

#define __RXX_ATTRIBUTE_FILTER_1(NAME) (NAME)
#define __RXX_ATTRIBUTE_FILTER_0(X)
#define __RXX_ATTRIBUTE_FILTER(NAME, ...) \
    RXX_PASTE(RXX_APPEND_IS_EMPTY(__RXX_ATTRIBUTE_FILTER_, __VA_ARGS__)(NAME))

#define __RXX_FILTER_CPP_ATTRIBUTES(ARGS) \
    RXX_SWAP_CONCAT(_END, __RXX_FILTER_CPP_ATTRIBUTES_1 ARGS)
#define __RXX_FILTER_CPP_ATTRIBUTES_1(NAME)                                   \
    __RXX_ATTRIBUTE_FILTER(NAME, RXX_CONCAT(__RXX_ATTRIBUTE_TYPE_CPP_, NAME)) \
    __RXX_FILTER_CPP_ATTRIBUTES_2
#define __RXX_FILTER_CPP_ATTRIBUTES_2(NAME)                                   \
    __RXX_ATTRIBUTE_FILTER(NAME, RXX_CONCAT(__RXX_ATTRIBUTE_TYPE_CPP_, NAME)) \
    __RXX_FILTER_CPP_ATTRIBUTES_1
#define __RXX_FILTER_CPP_ATTRIBUTES_1_END
#define __RXX_FILTER_CPP_ATTRIBUTES_2_END

#define __RXX_CPP_ATTRIBUTES(LIST)                        \
    __RXX_CPP_ATTRIBUTE_SCOPE(__RXX_BUILD_ATTRIBUTE_LIST( \
        __RXX_TRANSLATE_ATTRIBUTE(__RXX_FILTER_CPP_ATTRIBUTES(LIST))))

#define __RXX_FILTER_GNU_ATTRIBUTES(ARGS) \
    RXX_SWAP_CONCAT(_END, __RXX_FILTER_GNU_ATTRIBUTES_1 ARGS)
#define __RXX_FILTER_GNU_ATTRIBUTES_1(NAME)                                   \
    __RXX_ATTRIBUTE_FILTER(NAME, RXX_CONCAT(__RXX_ATTRIBUTE_TYPE_GNU_, NAME)) \
    __RXX_FILTER_GNU_ATTRIBUTES_2
#define __RXX_FILTER_GNU_ATTRIBUTES_2(NAME)                                   \
    __RXX_ATTRIBUTE_FILTER(NAME, RXX_CONCAT(__RXX_ATTRIBUTE_TYPE_GNU_, NAME)) \
    __RXX_FILTER_GNU_ATTRIBUTES_1
#define __RXX_FILTER_GNU_ATTRIBUTES_1_END
#define __RXX_FILTER_GNU_ATTRIBUTES_2_END

#define __RXX_GNU_ATTRIBUTES(LIST)                        \
    __RXX_GNU_ATTRIBUTE_SCOPE(__RXX_BUILD_ATTRIBUTE_LIST( \
        __RXX_TRANSLATE_ATTRIBUTE(__RXX_FILTER_GNU_ATTRIBUTES(LIST))))

#if RXX_SUPPORTS_DECLSPEC
#  define __RXX_FILTER_DECLSPEC_ATTRIBUTES(ARGS) \
      RXX_SWAP_CONCAT(_END, __RXX_FILTER_DECLSPEC_ATTRIBUTES_1 ARGS)
#  define __RXX_FILTER_DECLSPEC_ATTRIBUTES_1(NAME)                \
      __RXX_ATTRIBUTE_FILTER(                                     \
          NAME, RXX_CONCAT(__RXX_ATTRIBUTE_TYPE_DECLSPEC_, NAME)) \
      __RXX_FILTER_DECLSPEC_ATTRIBUTES_2
#  define __RXX_FILTER_DECLSPEC_ATTRIBUTES_2(NAME)                \
      __RXX_ATTRIBUTE_FILTER(                                     \
          NAME, RXX_CONCAT(__RXX_ATTRIBUTE_TYPE_DECLSPEC_, NAME)) \
      __RXX_FILTER_DECLSPEC_ATTRIBUTES_1
#  define __RXX_FILTER_DECLSPEC_ATTRIBUTES_1_END
#  define __RXX_FILTER_DECLSPEC_ATTRIBUTES_2_END

#  define __RXX_DECLSPEC(LIST)                         \
      __RXX_DECLSPEC_SCOPE(__RXX_BUILD_ATTRIBUTE_LIST( \
          __RXX_TRANSLATE_ATTRIBUTE(__RXX_FILTER_DECLSPEC_ATTRIBUTES(LIST))))
#else
#  define __RXX_DECLSPEC(LIST)
#endif

#define __RXX_ATOMIZE_ATTRIBUTE_1(NAME) RXX_CONCAT(__RXX_ATTRIBUTE_, NAME)
#define __RXX_ATOMIZE_ATTRIBUTE_0(NAME) (NAME)
#define __RXX_ATOMIZE_ATTRIBUTE(NAME)                       \
    RXX_PASTE(RXX_APPEND_IS_EMPTY(__RXX_ATOMIZE_ATTRIBUTE_, \
        RXX_CONCAT(__RXX_ATTRIBUTE_TYPE_AGGREGATE_, NAME))(NAME))

#define __RXX_ATTRIBUTE_ATOMIZATION(ARGS) \
    RXX_SWAP_CONCAT(_END, __RXX_ATTRIBUTE_ATOMIZATION_1 ARGS)
#if RXX_MSVC_PREPROCESSOR
#  define __RXX_ATTRIBUTE_ATOMIZATION_1(NAME) \
      RXX_PASTE(__RXX_ATOMIZE_ATTRIBUTE(NAME) __RXX_ATTRIBUTE_ATOMIZATION_2)
#  define __RXX_ATTRIBUTE_ATOMIZATION_2(NAME) \
      RXX_PASTE(__RXX_ATOMIZE_ATTRIBUTE(NAME) __RXX_ATTRIBUTE_ATOMIZATION_1)
#else
#  define __RXX_ATTRIBUTE_ATOMIZATION_1(NAME) \
      __RXX_ATOMIZE_ATTRIBUTE(NAME) __RXX_ATTRIBUTE_ATOMIZATION_2
#  define __RXX_ATTRIBUTE_ATOMIZATION_2(NAME) \
      __RXX_ATOMIZE_ATTRIBUTE(NAME) __RXX_ATTRIBUTE_ATOMIZATION_1
#endif
#define __RXX_ATTRIBUTE_ATOMIZATION_1_END
#define __RXX_ATTRIBUTE_ATOMIZATION_2_END

#define __RXX_EXPAND_ATOMIC_ATTRIBUTES(LIST) \
    __RXX_CPP_ATTRIBUTES(LIST)               \
    __RXX_GNU_ATTRIBUTES(LIST)               \
    __RXX_DECLSPEC(LIST)

#define __RXX_ATTRIBUTES(LIST) \
    __RXX_EXPAND_ATOMIC_ATTRIBUTES(__RXX_ATTRIBUTE_ATOMIZATION(LIST))

/**
 * Limit to 4 instead of using APPLY due to slow preprocessing
 */
#define __RXX_TO_ITERABLE_0(_0, _1, _2, _3, IMPL, ...) IMPL
#define __RXX_TO_ITERABLE(...)                                                 \
    __RXX_TO_ITERABLE_0(__VA_ARGS__, __RXX_TO_ITERABLE_4, __RXX_TO_ITERABLE_3, \
        __RXX_TO_ITERABLE_2, __RXX_TO_ITERABLE_1)                              \
    (__VA_ARGS__)
#define __RXX_TO_ITERABLE_4(_0, _1, _2, _3) (_0)(_1)(_2)(_3)
#define __RXX_TO_ITERABLE_3(_0, _1, _2) (_0)(_1)(_2)
#define __RXX_TO_ITERABLE_2(_0, _1) (_0)(_1)
#define __RXX_TO_ITERABLE_1(_0) (_0)

/**
 * Note: RXX_APPLY_MACRO slows down preprocessing by quite a bit
 * Compared with RXX_ATTRIBUTES disabled
 * preprocesses in ~3x without RXX_ATTRIBUTES when using __RXX_TO_ITERABLE
 * preprocesses in ~5x without RXX_ATTRIBUTES when using RXX_APPLY_MACRO
 */
#define RXX_ATTRIBUTES(...) __RXX_ATTRIBUTES(__RXX_TO_ITERABLE(__VA_ARGS__))
#define RXX_ATTRIBUTE(ATTR) __RXX_ATTRIBUTES((ATTR))

#define RXX_CPP_ATTRIBUTES(...) \
    __RXX_CPP_ATTRIBUTES(__RXX_TO_ITERABLE(__VA_ARGS__))
#define RXX_CPP_ATTRIBUTE(ATTR) __RXX_CPP_ATTRIBUTES((ATTR))

#define RXX_GNU_ATTRIBUTES(...) \
    __RXX_GNU_ATTRIBUTES(__RXX_TO_ITERABLE(__VA_ARGS__))
#define RXX_GNU_ATTRIBUTE(ATTR) __RXX_GNU_ATTRIBUTES((ATTR))

#define RXX_DECLSPEC_ATTRIBUTES(...) \
    __RXX_DECLSPEC(__RXX_TO_ITERABLE(__VA_ARGS__))
#define RXX_DECLSPEC_ATTRIBUTE(ATTR) __RXX_DECLSPEC((ATTR))

#define __RXX_NONEMPTY_ATTRIBUTE(ARG) !RXX_IS_EMPTY(ARG)
#define __RXX_HAS_ATTRIBUTE(ARGS)                                           \
    __RXX_NONEMPTY_ATTRIBUTE(__RXX_FILTER_CPP_ATTRIBUTES(ARGS)) ||          \
        __RXX_NONEMPTY_ATTRIBUTE(__RXX_FILTER_GNU_ATTRIBUTES(ARGS)) ||      \
        __RXX_NONEMPTY_ATTRIBUTE(__RXX_FILTER_DECLSPEC_ATTRIBUTES(ARGS)) || \
        __RXX_NONEMPTY_ATTRIBUTE(__RXX_FILTER_MSVC_EXT_ATTRIBUTES(ARGS))

#define RXX_HAS_ATTRIBUTE(NAME) \
    __RXX_HAS_ATTRIBUTE(__RXX_ATTRIBUTE_ATOMIZATION((NAME)))

#define RXX_HAS_AGGREGATE_ATTRIBUTE(NAME) \
    RXX_IS_EMPTY(RXX_CONCAT(__RXX_ATTRIBUTE_TYPE_AGGREGATE_, NAME))
